// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for macos - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.windows:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for windows - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      // case TargetPlatform.linux:
      //   throw UnsupportedError(
      //     'DefaultFirebaseOptions have not been configured for linux - '
      //     'you can reconfigure this by running the FlutterFire CLI again.',
      //   );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDU95fdd33OwqF2V_zQ1v50ogj_TV0yz_A",
  authDomain: "job-tracking-app-d38b2.firebaseapp.com",
  projectId: "job-tracking-app-d38b2",
  storageBucket: "job-tracking-app-d38b2.firebasestorage.app",
  messagingSenderId: "33805086987",
  appId: "1:33805086987:web:937066a0a2af9d8bf8320e",
  measurementId: "G-QMKMD5E79Q"
      );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU95fdd33OwqF2V_zQ1v50ogj_TV0yz_A',
    appId: '1:33805086987:web:937066a0a2af9d8bf8320e',
    messagingSenderId: '33805086987',
    projectId: 'job-tracking-app-d38b2',
    storageBucket: 'job-tracking-app-d38b2.firebasestorage.app',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDqCVsA1-xlHgNDhtSHpvI4qRM98zVBgOA',
  //   appId: '1:545059185697:ios:45f15c5756e4e9eda9af60',
  //   messagingSenderId: '545059185697',
  //   projectId: 'healthful-dev',
  //   storageBucket: 'healthful-dev.firebasestorage.app',
  //   iosBundleId: 'com.hifah.healthful',
  // );
}




 